<a href="https://colab.research.google.com/github/MarathaAshhhh/Events_Analysis/blob/main/tweets_extraact.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
pip install snscrape

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting snscrape
  Downloading snscrape-0.3.4-py3-none-any.whl (35 kB)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.7/dist-packages (from snscrape) (2.23.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.7/dist-packages (from snscrape) (4.6.3)
Requirement already satisfied: lxml in /usr/local/lib/python3.7/dist-packages (from snscrape) (4.9.1)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->snscrape) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->snscrape) (2022.9.24)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->snscrape) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->snscrape) (2.10)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->snscrape) (1.7.1)
Installing collected packages: snscrape
Successfully installed snscrape-0.3.4

In [ ]:
import snscrape.modules.twitter as sntwitter
import pandas as pd

In [ ]:

query = "It attending web3 lang:en until:2022-11-09 since:2017-11-19"
tweets = []
limit = 20000


for tweet in sntwitter.TwitterSearchScraper(query).get_items():
    
    # print(vars(tweet))
    # break
    if len(tweets) == limit:
        break
    else:
        tweets.append([tweet.content])
        
df = pd.DataFrame(tweets, columns=['Tweet'])
df

                                                 Tweet
0    Since I didn't get a @ryancarson POAP this mor...
1    @shaun_michaell @W3PokerClub 100% agree. Web3 ...
2    6/ #WebSummit was an incredible 3 days, with o...
3    @BennettHamiora There’s a digital art school i...
4    It was great attending the event by XORD at IB...
..                                                 ...
538  @alexavontobel @peteflint Love it, I believe t...
539  📅  Happening tomorrow in Toronto - The Web3 #U...
540  @nlw @EtherealSummit High compliments coming f...
541  If you’re attending @ethswarm #SwarmOrangeSumm...
542  1021 attending when the Reg portal was closed,...

[543 rows x 1 columns]

In [47]:
import snscrape.modules.twitter as sntwitter
import pandas as pd

query = "I attending web3 lang:en until:2022-11-09 since:2019-11-19"
tweets = []
limit = 20000


for tweet in sntwitter.TwitterSearchScraper(query).get_items():
    
    # print(vars(tweet))
    # break
    if len(tweets) == limit:
        break
    else:
        tweets.append([tweet.content])
        
df1 = pd.DataFrame(tweets, columns=['Tweet'])
df1

                                                  Tweet
0     I'm attending an online event with Amirhossein...
1     I am attending METACOMference | The Biggest We...
2     I'm attending an online event with @iambillsta...
3     I'm attending If you don’t have a web3 strateg...
4     I'm attending an online event with Amirhossein...
...                                                 ...
1866  I'm attending Introduction to Web3 (Virtual Ev...
1867  I'm attending @oscafrica's Introduction to Web...
1868  @alexavontobel @peteflint Love it, I believe t...
1869  I'm attending Open Source Festival  2020 . Joi...
1870  I'm attending Open Source Festival  2020 . Joi...

[1871 rows x 1 columns]

In [50]:
query = "I attend meetups lang:en until:2022-11-22 since:2017-10-16"
tweets = []
limit = 1500


for tweet in sntwitter.TwitterSearchScraper(query).get_items():
    
    # print(vars(tweet))
    # break
    if len(tweets) == limit:
        break
    else:
        tweets.append([tweet.content])
        
df2 = pd.DataFrame(tweets, columns=['Tweet'])
df2

                                                  Tweet
0     @chainhash_io @shardeum @NischalShetty @gregor...
1     walked by a pretty church today~ kyaaa the fan...
2     @TheSpinDoctor https://t.co/jWtm1qhBgR… might ...
3     @mynamesnotgordy @millerd99 Joined Meetups to ...
4     @shonojo And I just want a social where I can ...
...                                                 ...
1495  @lcmejia19 Thanks Luis! \n\nI’ve applied to 18...
1496  A6:  By making virtual instruction/meet-ups as...
1497  @SouthernerSays A4: No, but I attend meetups w...
1498  @mfaizfablillah used to carry around, asyik ti...
1499  @IamSnackless Thanks Snackless!!😄🤓 I wouldn't ...

[1500 rows x 1 columns]

In [ ]:
df2

                                                  Tweet
0     This is going to be huge event. I'm so happy t...
1     Can you believe that Cardano Summit is already...
2     It was a pleasure attending this year's #Websu...
3     @adeadringer83 @BoneheadLogic @JoJoFromJerz Ar...
4     Most aren't paying attention to this, but duri...
...                                                 ...
1449  Attending another Blockchain event, and it's j...
1450  @1_RebeccaThomas @cryptodemedici Don't know wh...
1451  RT akaAndre83: It's really great to be virtual...
1452  Attending the #SparkLabs #Demo #Day in #Seoul ...
1453  @danheld @coindesk My clients, who are getting...

[1454 rows x 1 columns]

In [53]:
df_positive = pd.concat([df1, df2, df3])

In [54]:
df_positive

                                                 Tweet
0    I'm attending an online event with Amirhossein...
1    I am attending METACOMference | The Biggest We...
2    I'm attending an online event with @iambillsta...
3    I'm attending If you don’t have a web3 strateg...
4    I'm attending an online event with Amirhossein...
..                                                 ...
838  @ConcatenateConf @unicodeveloper Please do, it...
839  Yes a nice TOA talk for everyone whi can‘t att...
840  I would love to attend but can’t afford it :-(...
841  Ways to learn more about #cryptocurrency:\n\n1...
842  @iiamtelo It may mean you're one of those the ...

[4214 rows x 1 columns]

In [48]:
import snscrape.modules.twitter as sntwitter
import pandas as pd

query = "It attend web3 lang:en until:2022-11-22 since:2017-10-16"
tweets = []
limit = 2000


for tweet in sntwitter.TwitterSearchScraper(query).get_items():
    
    # print(vars(tweet))
    # break
    if len(tweets) == limit:
        break
    else:
        tweets.append([tweet.content])
        
df3 = pd.DataFrame(tweets, columns=['Tweet'])
df3

                                                 Tweet
0    2. 👉Web3 lacks a personal touch (too many anon...
1    11/11 It is the start of the next session. \n\...
2    @PierreMetivier @borgetsebastien @TheSandboxGa...
3    Seberapa penting “Komunitas” dunia Web3 ? \n\n...
4    If given the chance, would you be interested t...
..                                                 ...
838  @ConcatenateConf @unicodeveloper Please do, it...
839  Yes a nice TOA talk for everyone whi can‘t att...
840  I would love to attend but can’t afford it :-(...
841  Ways to learn more about #cryptocurrency:\n\n1...
842  @iiamtelo It may mean you're one of those the ...

[843 rows x 1 columns]

In [ ]:
df= df.sample(frac=1)

In [ ]:
df["Attending_Score"]=1
df

                                                  Tweet  Attending_Score
0     I'm attending an online event with @0xNawarat ...                1
1     Before attending the event, I will admit that ...                1
2     @DcentralCon will celebrate web3 in Austin TX ...                1
3     I am attending @hashnode's Web3 space. Tune in...                1
4     I feel like I missed a lot in terms of $SOL NF...                1
...                                                 ...              ...
1952  I'm attending an online event with @PartnerWit...                1
1953  Attending Polygon Technology events is surely ...                1
1954  I am attending Shardeum Hyderabad Web3 Meetup ...                1
1955  @KeoneChong @alexpark @CallMeLatasha @sirsuhay...                1
1956  (4/18) I spend most of my days assisting my pa...                1

[1957 rows x 2 columns]

In [ ]:
df.astype(str).apply(lambda x: x.str.encode('ascii', 'ignore').str.decode('ascii'))

                                                  Tweet Attending_Score
0     I'm attending an online event with @0xNawarat ...               1
1     Before attending the event, I will admit that ...               1
2     @DcentralCon will celebrate web3 in Austin TX ...               1
3     I am attending @hashnode's Web3 space. Tune in...               1
4     I feel like I missed a lot in terms of $SOL NF...               1
...                                                 ...             ...
1952  I'm attending an online event with @PartnerWit...               1
1953  Attending Polygon Technology events is surely ...               1
1954  I am attending Shardeum Hyderabad Web3 Meetup ...               1
1955  @KeoneChong @alexpark @CallMeLatasha @sirsuhay...               1
1956  (4/18) I spend most of my days assisting my pa...               1

[1957 rows x 2 columns]

In [ ]:
query = "I attending events (going OR forward) -won't -unable lang:en until:2022-11-10 since:2018-08-17"
tweets = []
limit = 4000


for tweet in sntwitter.TwitterSearchScraper(query).get_items():
    
    # print(vars(tweet))
    # break
    if len(tweets) == limit:
        break
    else:
        tweets.append([tweet.content])
        
df_1 = pd.DataFrame(tweets, columns=['Tweet'])
df_1

                                                 Tweet
0    Unfortunately my wife was let go from both of ...
1    I won’t be at this one, likely just going stra...
2    Won't be attending the fantastic @ClassicMotor...
3    I guess she won't be attending or supporting a...
4    @DGodfatherMoody @TommeLVNV @BrandonJonesRac @...
..                                                 ...
565  I will be attending the event tomorrow in plac...
566  Sadly I will no longer be attending NYCC this ...
567  Absolutely appalling.  Shameful.  Do better @N...
568  Congregation Emanu El is hosting a hurricane H...
569  First time I’m promoting a techno event to fin...

[570 rows x 1 columns]

In [ ]:
df_3

NameError: ignored

In [ ]:
query = "I didn't attend web3 lang:en until:2022-11-09 since:2015-11-19"
tweets = []
limit = 20000


for tweet in sntwitter.TwitterSearchScraper(query).get_items():
    
    # print(vars(tweet))
    # break
    if len(tweets) == limit:
        break
    else:
        tweets.append([tweet.content])
        
df_2 = pd.DataFrame(tweets, columns=['Tweet'])
df_2

                                                Tweet
0   @MrRealWhale I have my gazed fixed on $ITHEUM ...
1   @DerekCoXX @polkastarter @mikegameiro It was s...
2   I didn't attend NFT London but see everything ...
3   8/n 💫\n5. @Worldwide_WEB3 Party\nThis is the m...
4   The CESC Zero-Knowledge Proof Workshop was hel...
5   I couldn’t make to attend the web3 conference ...
6   I have the AMAZING opportunity to attend not 1...
7   It's been busy at @CoinDesk, so I didn't do mu...
8   It was a right decision to attend this session...
9   IMMERSION OPPORTUNITY TO ATTEND A FREE CLASS! ...
10  I'm late for the announcement...I am shamed......
11  @CryptoFuzzyBTC @iznahere @Clubhouse When I fi...
12  Last week I attended the Global NFT Summit Lon...
13  Glover memorial hall, Marina. If you didn't at...
14  @AdamBombSquad @bobbyhundreds @BoredApeYC @tru...
15  🔥 I just went to the #Numbverse, and even thou...
16  @HurriCamee @kyledackerman hahaha I didn’t att...
17  @sellieyoung Thanks for this helpful summary f...
18  The day I was told I didn't have to attend mee...
19  Im grateful/blessed I had the opportunity to s...
20  @gate_io That was the video i was looking for!...
21  @VeefriendsU @veecon @garyvee I wasn’t an NFT ...
22  @cypheranarchist @tac_token @ThorNFTs @web3_ps...
23  @COLDSCOLLECTIVE @catalystbycc Didn't attend t...
24  What Billy said, “hype isn’t sustainable,” and...
25  Didn’t attend the town hall?  TLDR:  they’re b...
26  @codemathics @Stack_Shift Can’t believe all of...
27  I’ve seen so many people release POAPs and I’v...
28  I was positive to attend #WebSummit but I disa...
29  I didn’t go to Baccmass today—not because I go...

In [ ]:
query = "unable attend crypto lang:en until:2022-11-09 since:2015-11-19"
tweets = []
limit = 20000


for tweet in sntwitter.TwitterSearchScraper(query).get_items():
    
    # print(vars(tweet))
    # break
    if len(tweets) == limit:
        break
    else:
        tweets.append([tweet.content])
        
df_3 = pd.DataFrame(tweets, columns=['Tweet'])
df_3

                                                Tweet
0   @AlexiconTom Can you upload a video? I was una...
1   Nice one Team Utrust, It's always a pleasure t...
2   Thank you guys for joining us today. Together,...
3   To everyone who attended the opening reception...
4   We’re hosting an event in @spatialxr for those...
..                                                ...
70  @VVivekMittall99 @ThatNaimish @Bitcoin Dude pl...
71  @show_crypto Hi, Was unable to attend the show...
72  I've heard great feedback from past attendees ...
73  @DiaryofaMadeMan after so many years (crypto t...
74  @such_app Unfortunately I am unable to attend ...

[75 rows x 1 columns]

In [ ]:
query = "It attend meetups (unable OR not) lang:en until:2022-11-22 since:2017-10-16"
tweets = []
limit = 2000


for tweet in sntwitter.TwitterSearchScraper(query).get_items():
    
    # print(vars(tweet))
    # break
    if len(tweets) == limit:
        break
    else:
        tweets.append([tweet.content])
        
df_8 = pd.DataFrame(tweets, columns=['Tweet'])
df_8

                                                 Tweet
0    It has been tailored specifically for YOU!\nAs...
1    "thank you too." was what he said instead.\n\n...
2    @elevenmoonsdown The ladies were even nice eno...
3    Dear developers, remember:\n📌Do not quit\n📌Be ...
4    Dear developers, remember:\n📌Do not quit\n📌Be ...
..                                                 ...
324  @gutcave Well, that's not that bad~🙈 Do u have...
325  Hey #CUEchat getting my little to bed so I onl...
326  Don't know if it's the change in season, but a...
327  @Samcenafcb @massivebrains00 Btw, it's *all th...
328  It's not smart to attend your own friend meet ...

[329 rows x 1 columns]

In [ ]:
query = "I will attending events -web3 -crypto -bitcoin -ethereum lang:en until:2022-11-07 since:2018-10-16"
tweets = []
limit = 1500


for tweet in sntwitter.TwitterSearchScraper(query).get_items():
    
    # print(vars(tweet))
    # break
    if len(tweets) == limit:
        break
    else:
        tweets.append([tweet.content])
        
df_5 = pd.DataFrame(tweets, columns=['Tweet'])
df_5

                                                  Tweet
0     Sir, I will be there. Me as #Offchain London f...
1     I will be attending the Connecting the World F...
2     @CanLager @BrentPollution @anton_georgiou @Gre...
3     They better have an event on that day thats  t...
4     Attending #COP27 and I am so excited, honoured...
...                                                 ...
1495  Looking forward to seeing a great turn out of ...
1496  Tattershall Village Hall committee are hosting...
1497  I am getting ready for my favorite conference ...
1498  Due to lack of protection for the event, I wil...
1499  In 24 hours I will be arriving in Indy for @Ge...

[1500 rows x 1 columns]

In [ ]:
df_positive= pd.concat([df1, df3])

In [ ]:
query = "not attending web3 lang:en until:2022-11-07 since:2016-10-16"
tweets = []
limit = 2000


for tweet in sntwitter.TwitterSearchScraper(query).get_items():
    
    # print(vars(tweet))
    # break
    if len(tweets) == limit:
        break
    else:
        tweets.append([tweet.content])
        
df_6 = pd.DataFrame(tweets, columns=['Tweet'])
df_6

                                                 Tweet
0    Networking is such a powerful tool in web3.\n\...
1    @thrax_nft @web3_14159 Dao meeting that is.. s...
2    Attending this awesome hackathon #LumosHackDel...
3    Rumour has it there will be some special NFTs ...
4    🧵Thread 🧵\n\nAttending #GAM3R22 and #0xpoCross...
..                                                 ...
130  After attending NFT NYC,\n\nI’d like to double...
131  As a VC, it's frustrating when attending to he...
132  Attending the @usebraintrust Zoom Call.\nJust ...
133  The Portuguese web3 crew is hosting https://t....
134  Attending @blockstack’s talk about how web3 is...

[135 rows x 1 columns]

In [30]:
df_negation1= pd.concat([df_1, df_2, df_3, df_4, df_5 , df_6, df_7, df_8])

In [31]:
df_negation1

                                                 Tweet
0    Unfortunately my wife was let go from both of ...
1    I won’t be at this one, likely just going stra...
2    Won't be attending the fantastic @ClassicMotor...
3    I guess she won't be attending or supporting a...
4    @DGodfatherMoody @TommeLVNV @BrandonJonesRac @...
..                                                 ...
324  @gutcave Well, that's not that bad~🙈 Do u have...
325  Hey #CUEchat getting my little to bed so I onl...
326  Don't know if it's the change in season, but a...
327  @Samcenafcb @massivebrains00 Btw, it's *all th...
328  It's not smart to attend your own friend meet ...

[3567 rows x 1 columns]

In [38]:
df_2

                                                Tweet
0   @MrRealWhale I have my gazed fixed on $ITHEUM ...
1   @DerekCoXX @polkastarter @mikegameiro It was s...
2   I didn't attend NFT London but see everything ...
3   8/n 💫\n5. @Worldwide_WEB3 Party\nThis is the m...
4   The CESC Zero-Knowledge Proof Workshop was hel...
5   I couldn’t make to attend the web3 conference ...
6   I have the AMAZING opportunity to attend not 1...
7   It's been busy at @CoinDesk, so I didn't do mu...
8   It was a right decision to attend this session...
9   IMMERSION OPPORTUNITY TO ATTEND A FREE CLASS! ...
10  I'm late for the announcement...I am shamed......
11  @CryptoFuzzyBTC @iznahere @Clubhouse When I fi...
12  Last week I attended the Global NFT Summit Lon...
13  Glover memorial hall, Marina. If you didn't at...
14  @AdamBombSquad @bobbyhundreds @BoredApeYC @tru...
15  🔥 I just went to the #Numbverse, and even thou...
16  @HurriCamee @kyledackerman hahaha I didn’t att...
17  @sellieyoung Thanks for this helpful summary f...
18  The day I was told I didn't have to attend mee...
19  Im grateful/blessed I had the opportunity to s...
20  @gate_io That was the video i was looking for!...
21  @VeefriendsU @veecon @garyvee I wasn’t an NFT ...
22  @cypheranarchist @tac_token @ThorNFTs @web3_ps...
23  @COLDSCOLLECTIVE @catalystbycc Didn't attend t...
24  What Billy said, “hype isn’t sustainable,” and...
25  Didn’t attend the town hall?  TLDR:  they’re b...
26  @codemathics @Stack_Shift Can’t believe all of...
27  I’ve seen so many people release POAPs and I’v...
28  I was positive to attend #WebSummit but I disa...
29  I didn’t go to Baccmass today—not because I go...

In [39]:
df_positive

NameError: ignored

In [ ]:
df3 = pd.concat([df1, df])
df3

                                                  Tweet
0     I'm attending Blockchain &amp; Booze #137 - LA...
1     @NganKMacDonald, I.AIM Chief of Data Operation...
2     I am speaking at 2022 IEEE 1st Global Emerging...
3     Last week, I had the pleasure of attending and...
4     Ready for a busy first day at @token2049 Londo...
...                                                 ...
4995  @teamChromia is currently attending Defi Hacka...
4996  I am attending Blockchain Finance Lagos Confer...
4997  #XCARD is on the move again and attending Malt...
4998  Attending the 2019 National Asian Pacific Amer...
4999  Are you attending Blockchain Technology Summit...

[7656 rows x 1 columns]

In [ ]:
df_positive.to_csv('tweets_positive1.csv')

In [ ]:
df_negation.to_csv('tweets_negative.csv')

In [ ]:
df3.to_csv('tweets_crypto.csv')

In [ ]:
df3.drop(df3[df3['Tweet'] == 'Attending'].index, inplace = True)
print(df3)

                                                  Tweet
0     I'm attending Blockchain &amp; Booze #137 - LA...
1     @NganKMacDonald, I.AIM Chief of Data Operation...
2     I am speaking at 2022 IEEE 1st Global Emerging...
3     Last week, I had the pleasure of attending and...
4     Ready for a busy first day at @token2049 Londo...
...                                                 ...
4995  @teamChromia is currently attending Defi Hacka...
4996  I am attending Blockchain Finance Lagos Confer...
4997  #XCARD is on the move again and attending Malt...
4998  Attending the 2019 National Asian Pacific Amer...
4999  Are you attending Blockchain Technology Summit...

[7656 rows x 1 columns]

In [ ]:
df2 = df3[len(df3.Tweet) > 4]

KeyError: ignored

In [ ]:
df.to_csv('tweets.csv')

In [ ]:
df_negation["Attending_index"]= 0

In [ ]:
df_all = pd.concat([df_positive, df_negation])

In [ ]:
df_all

                                                 Tweet  Attending_index
0    I'm attending an online event with Amirhossein...                1
1    I am attending METACOMference | The Biggest We...                1
2    I'm attending an online event with @iambillsta...                1
3    I'm attending If you don’t have a web3 strateg...                1
4    Since I didn't get a @ryancarson POAP this mor...                1
..                                                 ...              ...
130  After attending NFT NYC,\n\nI’d like to double...                0
131  As a VC, it's frustrating when attending to he...                0
132  Attending the @usebraintrust Zoom Call.\nJust ...                0
133  The Portuguese web3 crew is hosting https://t....                0
134  Attending @blockstack’s talk about how web3 is...                0

[3826 rows x 2 columns]

In [ ]:
df_all = df_all.sample(frac=1).reset_index(drop=True)
df_all

                                                  Tweet  Attending_index
0     I could not echo this louder. TRU Band Room is...                0
1     I'm attending an online event  on the topic of...                1
2     Don't miss this exciting event! I will be atte...                0
3     @untapnl I will not be attending the event. I ...                0
4     We’re excited to be attending the #HCTExpo We ...                0
...                                                 ...              ...
3821  Damn I miss #EGX already... Met so many amazin...                0
3822  I am attending Web3 &amp; Blockchain Overview ...                1
3823  I am attending METACOMference | The Biggest We...                1
3824  I'm inviting D3, NAIA, JC, Prep, National JC's...                0
3825  I'm attending an online event with Enrico Mari...                1

[3826 rows x 2 columns]

In [ ]:
df_all.to_csv('Tweets_final.csv')

In [ ]:
df2.to_csv('Tweets_contrary.csv')

In [46]:
df_8

                                                 Tweet
0    It has been tailored specifically for YOU!\nAs...
1    "thank you too." was what he said instead.\n\n...
2    @elevenmoonsdown The ladies were even nice eno...
3    Dear developers, remember:\n📌Do not quit\n📌Be ...
4    Dear developers, remember:\n📌Do not quit\n📌Be ...
..                                                 ...
324  @gutcave Well, that's not that bad~🙈 Do u have...
325  Hey #CUEchat getting my little to bed so I onl...
326  Don't know if it's the change in season, but a...
327  @Samcenafcb @massivebrains00 Btw, it's *all th...
328  It's not smart to attend your own friend meet ...

[329 rows x 1 columns]

In [55]:
df_positive = df_positive.sample(frac=1).reset_index(drop=True)
df_positive

                                                  Tweet
0     I'm attending an online event with @0xEduard @...
1     @gabassodj @ZerozenStudios @LunaFreeCreates Sa...
2     I'm excited to attend web3con! Gonna be a cool...
3     I am attending Getting seen in web3 with Alec....
4     @florinpop1705 I would host lots of C# meetups...
...                                                 ...
4209  Today I will attend a great meetup\nAnd a grea...
4210  I'm attending an online event with @octogamex_...
4211  I wanna skip the last year of college and atte...
4212  I'm attending an online event with @iambillsta...
4213  Who's going to @MessariCrypto #mainnet2022 nex...

[4214 rows x 1 columns]

In [56]:
df_positive.drop(df.tail(600).index,
        inplace = True)

In [63]:
df_positive

                                                  Tweet  Attending_index
543   I'm attending an online event with @carv_offic...                1
544   @siddharth_hacks @storyblok @hackthisfall Hey ...                1
545   I will be attending @Blockchain_Expo , feel fr...                1
546   I will be attending the @JediSwap twitter spac...                1
547   I'm attending an online event on the topic of ...                1
...                                                 ...              ...
4209  Today I will attend a great meetup\nAnd a grea...                1
4210  I'm attending an online event with @octogamex_...                1
4211  I wanna skip the last year of college and atte...                1
4212  I'm attending an online event with @iambillsta...                1
4213  Who's going to @MessariCrypto #mainnet2022 nex...                1

[3671 rows x 2 columns]

In [62]:
df_negation

                                                 Tweet  Attending_index
0    Unfortunately my wife was let go from both of ...                0
1    I won’t be at this one, likely just going stra...                0
2    Won't be attending the fantastic @ClassicMotor...                0
3    I guess she won't be attending or supporting a...                0
4    @DGodfatherMoody @TommeLVNV @BrandonJonesRac @...                0
..                                                 ...              ...
324  @gutcave Well, that's not that bad~🙈 Do u have...                0
325  Hey #CUEchat getting my little to bed so I onl...                0
326  Don't know if it's the change in season, but a...                0
327  @Samcenafcb @massivebrains00 Btw, it's *all th...                0
328  It's not smart to attend your own friend meet ...                0

[3567 rows x 2 columns]

In [61]:
df_positive['Attending_index'] = 1
df_negation['Attending_index'] = 0

In [64]:
df_all= pd.concat([df_positive, df_negation])

In [65]:
df_all

                                                 Tweet  Attending_index
543  I'm attending an online event with @carv_offic...                1
544  @siddharth_hacks @storyblok @hackthisfall Hey ...                1
545  I will be attending @Blockchain_Expo , feel fr...                1
546  I will be attending the @JediSwap twitter spac...                1
547  I'm attending an online event on the topic of ...                1
..                                                 ...              ...
324  @gutcave Well, that's not that bad~🙈 Do u have...                0
325  Hey #CUEchat getting my little to bed so I onl...                0
326  Don't know if it's the change in season, but a...                0
327  @Samcenafcb @massivebrains00 Btw, it's *all th...                0
328  It's not smart to attend your own friend meet ...                0

[7238 rows x 2 columns]

In [66]:
df_all = df_all.sample(frac=1).reset_index(drop=True)
df_all

                                                  Tweet  Attending_index
0     @AdamDyster @GreenerUK_ @WCL_News Well, I look...                0
1     @theRSAorg Unfortunately, due to work commitme...                0
2     PrepHoopsTN Combine Campers: Our event is movi...                0
3     Community (in one form or another) and sharing...                0
4     I’m fortunate that I won’t be in trouble finan...                0
...                                                 ...              ...
7233  I'm attending an online event with @mottylen  ...                1
7234  A great time was had by all at the Gator Dugou...                0
7235  I was unable to attend the FFA breakfast this ...                0
7236  I'm attending an online event with @PartnerWit...                1
7237  @brucel @AndyDavies @matijagrcic I get it. Ppl...                1

[7238 rows x 2 columns]

In [67]:
df_all.to_csv('events_final.csv')